
import static java.awt.image.ImageObserver.HEIGHT;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author edwinfinch
 */
public class AccountForm extends javax.swing.JFrame {

    /**
     * Creates new form AccountForm
     */
    //Initialize the instance and set the framework accordingly
    public AccountForm(DataFramework newFrame) {
        initComponents();
        framework = newFrame;
        loggedInAsLabel.setText("Logged in as " + framework.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        loggedInAsLabel = new javax.swing.JLabel();
        viewSelfPostsButton = new javax.swing.JButton();
        viewOthersPostsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        launchWebVersionButton = new javax.swing.JButton();
        fedoratipLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(495, 530));
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Shree Devanagari 714", 0, 48)); // NOI18N
        titleLabel.setText("fedoratricks.com");

        loggedInAsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loggedInAsLabel.setText("Signed in as [error, no account]");

        viewSelfPostsButton.setText("View your posts");
        viewSelfPostsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSelfPostsButtonActionPerformed(evt);
            }
        });

        viewOthersPostsButton.setText("View another user's posts");
        viewOthersPostsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOthersPostsButtonActionPerformed(evt);
            }
        });

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        launchWebVersionButton.setText("Launch fedoratricks.com Web Version");
        launchWebVersionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchWebVersionButtonActionPerformed(evt);
            }
        });

        fedoratipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fedoratipLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fedora.jpg"))); // NOI18N
        fedoratipLabel.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(launchWebVersionButton)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(loggedInAsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(69, 69, 69))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(viewSelfPostsButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewOthersPostsButton)))
                            .addComponent(fedoratipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loggedInAsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewSelfPostsButton)
                    .addComponent(viewOthersPostsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fedoratipLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(launchWebVersionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public DataFramework framework;
    
    //Use the current framework to log out
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        boolean loggedOut = framework.logout();
        //Check the result. Should there be a weird error (ie. invalid token) it will warn the user
        if(loggedOut){
            LoginForm newLoginForm = new LoginForm();
            newLoginForm.framework = framework;
            newLoginForm.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Failed to log out. Try restarting Fedora Tricks Poster.", "Warning", HEIGHT);
        } 
    }//GEN-LAST:event_logoutButtonActionPerformed

    //Launches the web version of the site
    private void launchWebVersionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchWebVersionButtonActionPerformed
        try {
            framework.openWebPage(new URL("https://fedoratricks.com"));
        } catch (Exception e) { JOptionPane.showMessageDialog(rootPane, "Error launching webpage: " + e.getLocalizedMessage(), "Warning", HEIGHT); }
    }//GEN-LAST:event_launchWebVersionButtonActionPerformed

    //Grabs the username inputted by the user, checks if they exist, if they do loads their posts
    //Also checks if you try to view yourself
    private void viewOthersPostsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOthersPostsButtonActionPerformed
        String message = JOptionPane.showInputDialog(rootPane, "What's their username?");
        if(message.equals(framework.getUsername())){
            JOptionPane.showMessageDialog(rootPane, "Launch your own profile by clicking the \"View your posts\" button. \n It allows you to post.", "Warning", HEIGHT);
            return;
        }
        boolean exists = framework.usernameTaken(message);
        if(exists){
            UserContentWindow newWindow = new UserContentWindow();
            newWindow.username = message;
            System.out.println("username " + newWindow.username);
            newWindow.setVisible(true);
            newWindow.is_other_user = true;
            newWindow.refreshPosts(true);
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Error: user doesn't exist");
        }
    }//GEN-LAST:event_viewOthersPostsButtonActionPerformed

    //Allows you to view your own posts. Sets up a new content window, sets the framework
    //To the current instance and then refreshs the posts for the user automatically
    private void viewSelfPostsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSelfPostsButtonActionPerformed
        UserContentWindow newWindow = new UserContentWindow();
        newWindow.framework = framework;
        newWindow.username = framework.getUsername();
        newWindow.setVisible(true);
        newWindow.refreshPosts(true);
        
        //Debug
        //System.out.println(framework + " framework2 " + newWindow.framework);
    }//GEN-LAST:event_viewSelfPostsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fedoratipLabel;
    private javax.swing.JButton launchWebVersionButton;
    private javax.swing.JLabel loggedInAsLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton viewOthersPostsButton;
    private javax.swing.JButton viewSelfPostsButton;
    // End of variables declaration//GEN-END:variables
}
