
import java.util.regex.Pattern;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author edwinfinch
 */
public class CreateAccountForm extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccountForm
     */
    public CreateAccountForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField1 = new javax.swing.JPasswordField();
        passwordField2 = new javax.swing.JPasswordField();
        createButton = new javax.swing.JButton();
        errorSubtitle = new javax.swing.JLabel();
        fedoratricksFlair = new javax.swing.JLabel();
        usernameSubtitle = new javax.swing.JLabel();
        passwordSubtitle = new javax.swing.JLabel();
        confirmSubtitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        title.setFont(new java.awt.Font("Shree Devanagari 714", 0, 24)); // NOI18N
        title.setText("Create Account");

        passwordField2.setToolTipText("");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        errorSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorSubtitle.setText("Fedora Tricks isn't responsible for your actions.");

        fedoratricksFlair.setText("fedoratricks.com");

        usernameSubtitle.setText("Username");

        passwordSubtitle.setText("Password");

        confirmSubtitle.setText("Confirm Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createButton)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                    .addComponent(usernameSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordSubtitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameField)
                            .addComponent(passwordField2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(title)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fedoratricksFlair))
                            .addComponent(passwordField1)
                            .addComponent(confirmSubtitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fedoratricksFlair)
                    .addComponent(title))
                .addGap(18, 18, 18)
                .addComponent(usernameSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(passwordSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(passwordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmSubtitle)
                .addGap(4, 4, 4)
                .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorSubtitle)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DataFramework framework = new DataFramework();
    final String REQUIRED_PATTERN = "^[a-zA-Z0-9]*$";
    
    //Checks if the password matches syntax required (ie. 5-20 chars)
    public int passwordValid(){
        String p1 = new String(passwordField1.getPassword()), p2 = new String(passwordField2.getPassword());
        if(p1.equals(p2)){
            if(!(p1.length() > 4 && p1.length() < 20) || !(Pattern.matches(REQUIRED_PATTERN, p1))){
                return -2;
            }
        }
        else{
            return -1;
        }
        return 0;
    }
    //When the user asks to create an account, take the username and password and check them first
    //Then if that's all good ask the framework to create an account and output the result of that
    //If the account is created than open a new accountform for the user to manage their account with
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        String username = usernameField.getText(), password = new String(passwordField1.getPassword());
        switch(passwordValid()){
            case -1:
                errorSubtitle.setText("Passwords don't match.");
                return;
            case -2:
                errorSubtitle.setText("Passwords must use 5-20 letters/numbers.");
                return;
        }
        if (!(Pattern.matches(REQUIRED_PATTERN, username)) || username.length() < 5 || username.length() > 20) {
            errorSubtitle.setText("Usernames must use 5-20 letters/numbers.");
            return;
        }
        if(framework.usernameTaken(usernameField.getText())){
            errorSubtitle.setText("Username taken! Try again.");
            return;
        }
        errorSubtitle.setText("Valid input. Creating account...");
        
        boolean success = framework.createAccount(username, password);
        if(success){
            errorSubtitle.setText("Account created! Please wait...");
            if(framework.login(username, password)){
                /*
                framework.logout();
                LoginForm loginForm = new LoginForm();
                //loginForm.framework = framework;
                loginForm.setVisible(true);
                this.dispose();
                */
                AccountForm newWindow = new AccountForm(framework);
                newWindow.setVisible(true);
                errorSubtitle.setText("Logged in.");
                this.dispose();
                
            }
            else{
                errorSubtitle.setText("Failed to log in. Try logging in through login window.");
                LoginForm loginForm = new LoginForm();
                //loginForm.framework = framework;
                loginForm.setVisible(true);
                this.dispose(); 
           }
        }
        else{
            errorSubtitle.setText("Account creation failed! Try again...");
        }
    }//GEN-LAST:event_createButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel confirmSubtitle;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel errorSubtitle;
    private javax.swing.JLabel fedoratricksFlair;
    private javax.swing.JPasswordField passwordField1;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JLabel passwordSubtitle;
    private javax.swing.JLabel title;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameSubtitle;
    // End of variables declaration//GEN-END:variables
}
