/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author edwinfinch
 */
public class LinkPanel extends javax.swing.JPanel {

    /**
     * Creates new form LinkPanel
     */
    public LinkPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        linkTitle = new javax.swing.JLabel();
        linkInput = new javax.swing.JTextField();
        linkSubtitle = new javax.swing.JLabel();
        linkTextSubtitle = new javax.swing.JLabel();
        linkTextInput = new javax.swing.JTextField();
        postButton = new javax.swing.JButton();
        preview = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        linkTitle.setFont(new java.awt.Font("Shree Devanagari 714", 0, 18)); // NOI18N
        linkTitle.setText("Link Poster");

        linkInput.setText("https://fedoratricks.com");
        linkInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                linkInputKeyPressed(evt);
            }
        });

        linkSubtitle.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        linkSubtitle.setText("Link");

        linkTextSubtitle.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        linkTextSubtitle.setText("Link Text");

        linkTextInput.setText("Click for dope fedora tricks!");
        linkTextInput.setToolTipText("");
        linkTextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkTextInputActionPerformed(evt);
            }
        });
        linkTextInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                linkTextInputKeyPressed(evt);
            }
        });

        postButton.setText("Post");
        postButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postButtonActionPerformed(evt);
            }
        });

        preview.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        preview.setForeground(new java.awt.Color(0, 153, 255));
        preview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(linkInput, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(linkTextInput, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(linkTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(linkSubtitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(linkTextSubtitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(postButton)))
                        .addGap(0, 178, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linkTitle)
                .addGap(11, 11, 11)
                .addComponent(linkSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkTextSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linkTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preview, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    DataFramework framework;
    //Just shows a simple preview of the text before actually being sent
    private void renderPreview(){
        preview.setText("Preview: " + linkTextInput.getText());
    }
    
    //Again with the condensing, but anyway
    //Renders the preview whenever an action is occurred on the input types
    private void linkInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linkInputKeyPressed
        renderPreview();
    }//GEN-LAST:event_linkInputKeyPressed

    private void linkTextInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkTextInputActionPerformed
        renderPreview();
    }//GEN-LAST:event_linkTextInputActionPerformed

    private void linkTextInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linkTextInputKeyPressed
        renderPreview();
    }//GEN-LAST:event_linkTextInputKeyPressed

    //When try to post, output the result of it to the user
    private void postButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postButtonActionPerformed
        int result = framework.postLink(linkInput.getText(), linkTextInput.getText());
        switch(result){
            case 0:
                linkTitle.setText("Post success");
                break;
            case -1:
                linkTitle.setText("Failed: Invalid parameters");
                break;
            case -2:
                linkTitle.setText("Failed: Invalid credentials");
                break;
            case -3:
                linkTitle.setText("Failed: Internal error");
                break;
        }
    }//GEN-LAST:event_postButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField linkInput;
    private javax.swing.JLabel linkSubtitle;
    private javax.swing.JTextField linkTextInput;
    private javax.swing.JLabel linkTextSubtitle;
    private javax.swing.JLabel linkTitle;
    private javax.swing.JButton postButton;
    private javax.swing.JLabel preview;
    // End of variables declaration//GEN-END:variables
}
